notify = ["bun", "/Users/timo/.codex/hooks/notify-all.ts"]

[features]
web_search_request = true

[sandbox_workspace_write]
network_access = true

# [mcp_servers.playwright]
# command = "npx"
# args = ["@playwright/mcp@latest"]

# [mcp_servers.fetch]
# command = "uvx"
# args = ["mcp-server-fetch"]

# [mcp_servers.ios-simulator]
# command = "npx"
# args = ["-y", "ios-simulator-mcp"]

# [mcp_servers.framelink-figma-mcp]
# command = "npx"
# args = [
#   "-y",
#   "figma-developer-mcp",
#   "--stdio"
# ]
